apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sock-shop
resources:
  - ../../../base/sock-shop
patches:
  - patch: |-
      - op: replace
        path: /spec/path
        value: ./deploy/kubernetes/overlays/development
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta2
      kind: Kustomization
      name: sock-shop-tenant